import Link from "next/link";

import "./globals.css";

import Header from "./components/Header"
import Article from "./components/Article"
import Section from "./components/Section"
import Footer from "./components/Footer";


export const metadata = {
  title: "Oposositiones esquemas",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="es">
      <body>
        <Header url={"/logo/instagram.png"} />
        <div className="View">

          <Section>
            <Article url={"/images/freestocks.jpg"} />
            <Article url={"/images/henry.jpg"} />
            <Article url={"/images/prophsee.jpg"} />
            <Article url={"/images/daria.jpg"} />
          </Section>

        </div>
        <Footer />
      </body>
    </html >
  );
}
